### ISSUE TITLE
[Feature] cellfinder training save iterations by default and reduce epoch number

### ISSUE THREAD

**Issue by stephenlenzi** [SainsburyWellcomeCentre/cellfinder#97]
**Is your feature request related to a problem? Please describe.**

I sometimes accidentally run cellfinder without saving intermediate stages and it takes a long time without saving outputs, means I have to cancel and restart.

**Describe the solution you'd like**

I think it would be useful to change the default behaviour of cellfinder train to a lower number of epochs and/or to save intermediate models by default

**Comment by adamltyson** [comment]
The default behavior is now to save checkpoints after each epoch (cf54820bc409b493a05b62a96c83e0bd321372ed). Use `--no-save-checkpoints` to suppress this behavior. Models can be very big, and if you don't have much training data, they can be generated quickly.

I'm leaving the default number of epochs as 100. It's hard to pick a number because a single epoch can take 15 seconds or 12 hours, depending on the data. At least with a high number you can cancel.  

You can also use `--save-progress` to save training progress to a .csv file (`output_directory/training.csv`).
